### ISSUE TITLE
Calls to dice_roll are very slow

### ISSUE THREAD

**Issue by sujaldev** [identex/quantumrand#2]
Hi, I was using thing library and was getting quite slow speeds so I checked the source code and it seems like you are creating a `cached_generator` for every call to `dice_roll` here:
https://github.com/identex/quantumrand/blob/0baaf1b94f74ae5b860a263d880f344d032879e0/quantumrand/__init__.py#L148

Forgive me if I am wrong but isn't that doing the opposite of what its supposed to, slowing down instead of speeding up further calls?

**Comment by breadbored** [comment]
Hi @sujaldev, thanks for raising this issue.

This was meant to fetch a seed from ANU's server and use that seed locally multiple times. However, it appears to be an oversight on my end. You're right, I'm calling the server every call. I see your PR and will review and potentially merge soon.

PR https://github.com/identex/quantumrand/pull/3

**Comment by breadbored** [comment]
This is being uploaded to PyPi now.

Edit: It is now available at https://pypi.org/project/quantumrand/2.2.0/
